function pug_attr(t,e,n,r){if(!1===e||null==e||!e&&("class"===t||"style"===t))return"";if(!0===e)return" "+(r?t:t+'="'+t+'"');var f=typeof e;return"object"!==f&&"function"!==f||"function"!=typeof e.toJSON||(e=e.toJSON()),"string"==typeof e||(e=JSON.stringify(e),n||-1===e.indexOf('"'))?(n&&(e=pug_escape(e))," "+t+'="'+e+'"'):" "+t+"='"+e.replace(/'/g,"&#39;")+"'"}
function pug_escape(e){var a=""+e,t=pug_match_html.exec(a);if(!t)return e;var r,c,n,s="";for(r=t.index,c=0;r<a.length;r++){switch(a.charCodeAt(r)){case 34:n="&quot;";break;case 38:n="&amp;";break;case 60:n="&lt;";break;case 62:n="&gt;";break;default:continue}c!==r&&(s+=a.substring(c,r)),c=r+1,s+=n}return c!==r?s+a.substring(c,r):s}
var pug_match_html=/["&<>]/;
function pug_rethrow(e,n,r,t){if(!(e instanceof Error))throw e;if(!("undefined"==typeof window&&n||t))throw e.message+=" on line "+r,e;var o,a,i,s;try{t=t||require("fs").readFileSync(n,{encoding:"utf8"}),o=3,a=t.split("\n"),i=Math.max(r-o,0),s=Math.min(a.length,r+o)}catch(t){return e.message+=" - could not read from "+n+" ("+t.message+")",void pug_rethrow(e,null,r)}o=a.slice(i,s).map(function(e,n){var t=n+i+1;return(t==r?"  > ":"    ")+t+"| "+e}).join("\n"),e.path=n;try{e.message=(n||"Pug")+":"+r+"\n"+o+"\n\n"+e.message}catch(e){}throw e}function send(locals) {var pug_html = "", pug_mixins = {}, pug_interp;var pug_debug_filename, pug_debug_line;try {;
    var locals_for_with = (locals || {});
    
    (function (send, title, transfers) {
      ;pug_debug_line = 1;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "\u003C!DOCTYPE html\u003E";
;pug_debug_line = 2;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "\u003Chtml lang=\"en\"\u003E";
;pug_debug_line = 3;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "\u003Chead\u003E";
;pug_debug_line = 4;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "\u003Cmeta charset=\"UTF-8\"\u003E";
;pug_debug_line = 5;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "\u003Cmeta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\"\u003E";
;pug_debug_line = 6;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "\u003Cmeta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"\u003E";
;pug_debug_line = 7;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "\u003Ctitle\u003E";
;pug_debug_line = 7;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + (pug_escape(null == (pug_interp = title) ? "" : pug_interp)) + "\u003C\u002Ftitle\u003E\u003C\u002Fhead\u003E";
;pug_debug_line = 8;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "\u003Cbody\u003E";
;pug_debug_line = 8;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + " ";
;pug_debug_line = 1;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\layout.pug";
pug_html = pug_html + "\u003C!DOCTYPE html\u003E";
;pug_debug_line = 2;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\layout.pug";
pug_html = pug_html + "\u003Chtml lang=\"en\"\u003E";
;pug_debug_line = 3;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\layout.pug";
pug_html = pug_html + "\u003Chead\u003E";
;pug_debug_line = 4;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\layout.pug";
pug_html = pug_html + "\u003Cmeta charset=\"UTF-8\"\u003E";
;pug_debug_line = 5;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\layout.pug";
pug_html = pug_html + "\u003Cmeta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\"\u003E";
;pug_debug_line = 6;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\layout.pug";
pug_html = pug_html + "\u003Cmeta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"\u003E";
;pug_debug_line = 7;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\layout.pug";
pug_html = pug_html + "\u003Ctitle\u003E";
;pug_debug_line = 7;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\layout.pug";
pug_html = pug_html + (pug_escape(null == (pug_interp = title) ? "" : pug_interp)) + "\u003C\u002Ftitle\u003E\u003C\u002Fhead\u003E";
;pug_debug_line = 8;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\layout.pug";
pug_html = pug_html + "\u003Cbody\u003E";
;pug_debug_line = 8;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\layout.pug";
pug_html = pug_html + " ";
;pug_debug_line = 9;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\layout.pug";
pug_html = pug_html + "\u003Cnav class=\"navbar\"\u003E";
;pug_debug_line = 10;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\layout.pug";
pug_html = pug_html + "\u003Cul\u003E";
;pug_debug_line = 11;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\layout.pug";
pug_html = pug_html + "\u003Cli class=\"item\"\u003E";
;pug_debug_line = 12;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\layout.pug";
pug_html = pug_html + "\u003Cdiv id=\"logo\"\u003E\u003C\u002Fdiv\u003E\u003C\u002Fli\u003E";
;pug_debug_line = 14;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\layout.pug";
pug_html = pug_html + "\u003Cli class=\"item\"\u003E";
;pug_debug_line = 15;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\layout.pug";
pug_html = pug_html + "\u003Ca href=\"\u002F\"\u003E";
;pug_debug_line = 15;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\layout.pug";
pug_html = pug_html + "Home\u003C\u002Fa\u003E\u003C\u002Fli\u003E";
;pug_debug_line = 17;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\layout.pug";
pug_html = pug_html + "\u003Cli class=\"item\"\u003E";
;pug_debug_line = 18;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\layout.pug";
pug_html = pug_html + "\u003Ca href=\"\u002Fallusers\"\u003E";
;pug_debug_line = 18;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\layout.pug";
pug_html = pug_html + "All Users\u003C\u002Fa\u003E\u003C\u002Fli\u003E";
;pug_debug_line = 20;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\layout.pug";
pug_html = pug_html + "\u003Cli class=\"item\"\u003E";
;pug_debug_line = 21;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\layout.pug";
pug_html = pug_html + "\u003Ca href=\"\u002Ftransfer\"\u003E";
;pug_debug_line = 21;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\layout.pug";
pug_html = pug_html + "Transfer\u003C\u002Fa\u003E\u003C\u002Fli\u003E";
;pug_debug_line = 23;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\layout.pug";
pug_html = pug_html + "\u003Cli class=\"item\"\u003E";
;pug_debug_line = 24;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\layout.pug";
pug_html = pug_html + "\u003Ca href=\"\u002Ftransaction\"\u003E";
;pug_debug_line = 24;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\layout.pug";
pug_html = pug_html + "Transaction History\u003C\u002Fa\u003E\u003C\u002Fli\u003E\u003C\u002Ful\u003E\u003C\u002Fnav\u003E\u003C\u002Fbody\u003E\u003C\u002Fhtml\u003E";
;pug_debug_line = 11;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "\u003Ch1\u003E";
;pug_debug_line = 11;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "Transfer\u003C\u002Fh1\u003E";
;pug_debug_line = 13;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "\u003Cform id=\"form\" action=\"\u002Ftransfer\" method=\"POST\"\u003E";
;pug_debug_line = 14;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "\u003Cdiv class=\"container\"\u003E";
;pug_debug_line = 14;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + " ";
;pug_debug_line = 15;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "\u003Cselect id=\"sender\" name=\"sendername\"\u003E";
;pug_debug_line = 16;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "\u003Coption" + (pug_attr("disabled", true, true, true)+pug_attr("selected", true, true, true)+pug_attr("hidden", true, true, true)) + "\u003E";
;pug_debug_line = 16;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "Select Sender\u003C\u002Foption\u003E";
;pug_debug_line = 17;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "\u003Coption value=\"Lisa\"\u003E";
;pug_debug_line = 17;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "Lisa \u003C\u002Foption\u003E";
;pug_debug_line = 18;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "\u003Coption value=\"Mack\"\u003E";
;pug_debug_line = 18;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "Mack \u003C\u002Foption\u003E";
;pug_debug_line = 19;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "\u003Coption value=\"Rossie\"\u003E";
;pug_debug_line = 19;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "Rossie \u003C\u002Foption\u003E";
;pug_debug_line = 20;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "\u003Coption value=\"Xiao\"\u003E";
;pug_debug_line = 20;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "Xiao \u003C\u002Foption\u003E";
;pug_debug_line = 21;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "\u003Coption value=\"Bei\"\u003E";
;pug_debug_line = 21;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "Bei \u003C\u002Foption\u003E";
;pug_debug_line = 22;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "\u003Coption value=\"Benny\"\u003E";
;pug_debug_line = 22;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "Benny \u003C\u002Foption\u003E";
;pug_debug_line = 23;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "\u003Coption value=\"Reema\"\u003E";
;pug_debug_line = 23;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "Reema \u003C\u002Foption\u003E";
;pug_debug_line = 24;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "\u003Coption value=\"Kevin\"\u003E";
;pug_debug_line = 24;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "Kevin \u003C\u002Foption\u003E";
;pug_debug_line = 25;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "\u003Coption value=\"Christle\"\u003E";
;pug_debug_line = 25;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "Christle \u003C\u002Foption\u003E";
;pug_debug_line = 26;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "\u003Coption value=\"Denie\"\u003E";
;pug_debug_line = 26;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "Denie \u003C\u002Foption\u003E\u003C\u002Fselect\u003E\u003C\u002Fdiv\u003E";
;pug_debug_line = 28;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "\u003Cselect" + (" class=\"hide\""+" id=\"senderbal\" name=\"senderbal\""+pug_attr("disabled", true, true, true)) + "\u003E";
;pug_debug_line = 29;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "\u003Coption" + (pug_attr("value", `${transfers.balance}`, true, true)+pug_attr("selected", true, true, true)+pug_attr("hidden", true, true, true)) + "\u003E";
;pug_debug_line = 29;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + (pug_escape(null == (pug_interp = transfers.balance) ? "" : pug_interp));
;pug_debug_line = 29;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + " \u003C\u002Foption\u003E\u003C\u002Fselect\u003E\u003C\u002Fform\u003E";
;pug_debug_line = 31;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "\u003Clabel class=\"lab\" for=\"transfer\"\u003E";
;pug_debug_line = 31;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "Transfer To:";
;pug_debug_line = 33;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "\u003Cdiv class=\"container\"\u003E";
;pug_debug_line = 33;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + " ";
;pug_debug_line = 34;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "\u003Cselect id=\"receiver\" name=\"name\"\u003E";
;pug_debug_line = 35;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "\u003Coption" + (pug_attr("disabled", true, true, true)+pug_attr("selected", true, true, true)+pug_attr("hidden", true, true, true)) + "\u003E";
;pug_debug_line = 35;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "Select receiver \u003C\u002Foption\u003E";
;pug_debug_line = 36;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "\u003Coption value=\"Lisa\"\u003E";
;pug_debug_line = 36;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "Lisa \u003C\u002Foption\u003E";
;pug_debug_line = 37;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "\u003Coption value=\"Mack\"\u003E";
;pug_debug_line = 37;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "Mack \u003C\u002Foption\u003E";
;pug_debug_line = 38;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "\u003Coption value=\"Rossie\"\u003E";
;pug_debug_line = 38;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "Rossie \u003C\u002Foption\u003E";
;pug_debug_line = 39;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "\u003Coption value=\"Xiao\"\u003E";
;pug_debug_line = 39;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "Xiao \u003C\u002Foption\u003E";
;pug_debug_line = 40;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "\u003Coption value=\"Bei\"\u003E";
;pug_debug_line = 40;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "Bei \u003C\u002Foption\u003E";
;pug_debug_line = 41;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "\u003Coption value=\"Benny\"\u003E";
;pug_debug_line = 41;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "Benny \u003C\u002Foption\u003E";
;pug_debug_line = 42;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "\u003Coption value=\"Reema\"\u003E";
;pug_debug_line = 42;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "Reema \u003C\u002Foption\u003E";
;pug_debug_line = 43;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "\u003Coption value=\"Kevin\"\u003E";
;pug_debug_line = 43;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "Kevin \u003C\u002Foption\u003E";
;pug_debug_line = 44;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "\u003Coption value=\"Christle\"\u003E";
;pug_debug_line = 44;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "Christle \u003C\u002Foption\u003E";
;pug_debug_line = 45;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "\u003Coption value=\"Denie\"\u003E";
;pug_debug_line = 45;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "Denie \u003C\u002Foption\u003E\u003C\u002Fselect\u003E\u003C\u002Fdiv\u003E\u003C\u002Flabel\u003E";
;pug_debug_line = 47;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "\u003Clabel class=\"lab\" for=\"amount\"\u003E";
;pug_debug_line = 47;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "Enter Amount: \u003C\u002Flabel\u003E";
;pug_debug_line = 49;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "\u003Cinput id=\"amount\" type=\"number\" name=\"amount\" placeholder=\"Amount\"\u003E";
;pug_debug_line = 51;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "\u003Cbutton" + (" class=\"btn\""+pug_attr("onclick", send(), true, true)) + "\u003E";
;pug_debug_line = 51;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "Send\u003C\u002Fbutton\u003E";
;pug_debug_line = 52;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "\u003Cbutton class=\"btn\"\u003E";
;pug_debug_line = 52;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + " ";
;pug_debug_line = 53;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "\u003Ca href=\"\u002Fallusers\"\u003E";
;pug_debug_line = 53;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "Back \u003C\u002Fa\u003E\u003C\u002Fbutton\u003E";
;pug_debug_line = 55;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "\u003Cscript\u003E";
;pug_debug_line = 56;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "function(send) {";
;pug_debug_line = 57;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "\n";
;pug_debug_line = 57;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "  var money = parseInt(document.getElementById(\"amount\").value);";
;pug_debug_line = 58;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "\n";
;pug_debug_line = 58;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "  console.log(money)";
;pug_debug_line = 59;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "\n";
;pug_debug_line = 59;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "  var bal = parseInt(document.getElementById(\"senderbal\").innerHTML);";
;pug_debug_line = 60;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "\n";
;pug_debug_line = 60;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "  console.log(bal)";
;pug_debug_line = 61;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "\n";
;pug_debug_line = 61;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "  if money \u003C= 0 ";
;pug_debug_line = 62;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "\n";
;pug_debug_line = 62;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "  alert(\"Please enter a real amount\")";
;pug_debug_line = 63;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "\n";
;pug_debug_line = 63;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "  else if money \u003E bal ";
;pug_debug_line = 64;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "\n";
;pug_debug_line = 64;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "  alert(\"Insufficient Balance\")";
;pug_debug_line = 65;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "\n";
;pug_debug_line = 65;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "  else ";
;pug_debug_line = 66;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "\n";
;pug_debug_line = 66;pug_debug_filename = "F:\\expressapp\\bhrgbank\\views\\transfer.pug";
pug_html = pug_html + "  alert(\"Transfer Succesfully Done\")\u003C\u002Fscript\u003E\u003C\u002Fbody\u003E\u003C\u002Fhtml\u003E";
    }.call(this, "send" in locals_for_with ?
        locals_for_with.send :
        typeof send !== 'undefined' ? send : undefined, "title" in locals_for_with ?
        locals_for_with.title :
        typeof title !== 'undefined' ? title : undefined, "transfers" in locals_for_with ?
        locals_for_with.transfers :
        typeof transfers !== 'undefined' ? transfers : undefined));
    ;} catch (err) {pug_rethrow(err, pug_debug_filename, pug_debug_line);};return pug_html;}